# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Example
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  tasks:
    - name: Information about all products
      phoenixnap.bmc.product_availability_info:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
      register: output
    - name: Print the gathered infos
      ansible.builtin.debug:
        var: output.product_availabilities

    - name: Information about all server products at the Phoenix location
      phoenixnap.bmc.product_availability_info:
        client_id: "{{ clientId }}"
        client_secret: "{{ clientSecret }}"
        product_category:
          - SERVER
        location:
          - PHX
      register: output
    - name: Print the gathered infos filtered by location
      ansible.builtin.debug:
        var: output.product_availabilities
