---
objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory:
    bmc_server:
      description: Retrieves list of servers via PhoenixNAP BMC API
      name: bmc_server
      version_added: 1.17.0
  lookup: {}
  module:
    bgp_peer_group:
      description: Create/delete BGP Peer Group. on phoenixNAP Bare Metal Cloud.
      name: bgp_peer_group
      namespace: ""
      version_added: 1.18.0
    bgp_peer_group_info:
      description: Gather information about phoenixNAP BGP Peer Groups owned by account.
      name: bgp_peer_group_info
      namespace: ""
      version_added: 1.18.0
    cluster:
      description: Manage phoenixNAP Bare Metal Cloud clusters
      name: cluster
      namespace: ""
      version_added: 1.1.0
    cluster_info:
      description: Gather information about phoenixNAP clusters
      name: cluster_info
      namespace: ""
      version_added: 1.1.0
    event_info:
      description: Retrieves the event logs for given time period.
      name: event_info
      namespace: ""
      version_added: 1.0.0
    invoice_info:
      description: List invoices.
      name: invoice_info
      namespace: ""
      version_added: 1.17.0
    ip_block:
      description: Create/delete IP block.
      name: ip_block
      namespace: ""
      version_added: 1.2.0
    ip_block_info:
      description: Gather information about phoenixNAP public IP blocks.
      name: ip_block_info
      namespace: ""
      version_added: 1.2.0
    private_network:
      description: Create/delete private network on phoenixNAP Bare Metal Cloud.
      name: private_network
      namespace: ""
      version_added: "0.11.0"
    private_network_info:
      description: Gather information about phoenixNAP BMC private networks
      name: private_network_info
      namespace: ""
      version_added: "0.11.0"
    product_availability_info:
      description: Gather information about products availability
      name: product_availability_info
      namespace: ""
      version_added: 1.3.0
    product_info:
      description: Gather information about phoenixNAP BMC products
      name: product_info
      namespace: ""
      version_added: 1.3.0
    public_network:
      description: Create/delete public network on phoenixNAP Bare Metal Cloud.
      name: public_network
      namespace: ""
      version_added: 1.5.0
    public_network_info:
      description: Gather information about phoenixNAP BMC public networks
      name: public_network_info
      namespace: ""
      version_added: 1.5.0
    public_network_ip_block:
      description: add/remove an IP block from a public network.
      name: public_network_ip_block
      namespace: ""
      version_added: 1.11.0
    rated_usage_info:
      description: Retrieves all rated usage for given time period.
      name: rated_usage_info
      namespace: ""
      version_added: 1.15.0
    reservation:
      description: Create reservation on phoenixNAP Bare Metal Cloud.
      name: reservation
      namespace: ""
      version_added: 1.0.0
    reservation_info:
      description: Gather information about phoenixNAP BMC reservations
      name: reservation_info
      namespace: ""
      version_added: 1.0.0
    server:
      description: Manage phoenixNAP Bare Metal Cloud servers
      name: server
      namespace: ""
      version_added: "0.5.0"
    server_info:
      description: Gather information about phoenixNAP BMC servers
      name: server_info
      namespace: ""
      version_added: "0.7.0"
    server_ip_block:
      description: add/remove an IP block from a server.
      name: server_ip_block
      namespace: ""
      version_added: 1.10.0
    server_private_network:
      description: add/remove the server to/from a private network
      name: server_private_network
      namespace: ""
      version_added: 1.10.0
    server_public_network:
      description: add/remove the server to/from a public network
      name: server_public_network
      namespace: ""
      version_added: 1.10.0
    server_reserve:
      description: reserve specific server.
      name: server_reserve
      namespace: ""
      version_added: 1.15.0
    server_reserved:
      description: Provision reserved server.
      name: server_reserved
      namespace: ""
      version_added: 1.16.0
    ssh_key:
      description: Create/delete SSH key on phoenixNAP Bare Metal Cloud.
      name: ssh_key
      namespace: ""
      version_added: "0.5.0"
    ssh_key_info:
      description: Gather information about phoenixNAP BMC SSH Keys
      name: ssh_key_info
      namespace: ""
      version_added: "0.7.0"
    storage_network:
      description: Create/delete storage network on phoenixNAP Bare Metal Cloud.
      name: storage_network
      namespace: ""
      version_added: 1.6.0
    storage_network_info:
      description: Gather information about phoenixNAP BMC storage networks
      name: storage_network_info
      namespace: ""
      version_added: 1.6.0
    storage_network_volume:
      description: add/remove Volume from a Storage Network.
      name: storage_network_volume
      namespace: ""
      version_added: 1.11.0
    tag:
      description: Create/delete tag on phoenixNAP Bare Metal Cloud.
      name: tag
      namespace: ""
      version_added: "0.12.0"
    tag_info:
      description: Gather information about phoenixNAP BMC tags
      name: tag_info
      namespace: ""
      version_added: "0.12.0"
    transaction_info:
      description: List of client's transactions.
      name: transaction_info
      namespace: ""
      version_added: 1.17.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.18.0
