# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Create new ESXi server
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  collections:
    - phoenixnap.bmc
  tasks:
  - phoenixnap.bmc.server:
      client_id: "{{clientId}}"
      client_secret: "{{clientSecret}}"
      hostnames: [my-server-1]
      location: PHX
      os: esxi/esxi70u2
      type: s0.d1.medium
      state: present 
      management_access_allowed_ips: 
        - xx.xxx.xxx.xx
        - yy.yyy.yyy.yy